### PR TITLE
move schemars to separate CI job

### PR DESCRIPTION
**Pull request by apoelstra**
and run it on nightly only

If it breaks again we'll set it to "allow fail".

### CODE REVIEW

**Review by tcharding — APPROVED** [review]
ACK d0a77d6f9f4d5f70c306290f15a6a8dbf7575101

This is still going to build the `schemars` feature in other jobs - do we want to limit that to this job also?

**Comment by apoelstra** [comment]
@tcharding good catch. I think for now it's ok. The issue here is that the extra schemars test has a pile of bad dependencies of its own, even beyond schemars itself.

**Comment by tcharding** [comment]
Sweet, cheers.

**Comment by Kixunil** [comment]
Concept ACK, why nightly though? Yes, we may catch and report Rust error which is noble but I don't think we should fail CI if something breaks. Perhaps allow fail on nightly and disallow fail on stable?

**Comment by apoelstra** [comment]
>why nightly though

It seemed least likely to break again. Maybe `stable` would've been a better choice?

**Review by Kixunil — APPROVED** [review]
ACK 64c085cde284fad572a1f8429abc4331f61b44e9

**Comment by Kixunil** [comment]
Oh, actually this changes MSRV of `shemars` to `stable`. Would be better to document that.

**Comment by apoelstra** [comment]
There has never been a `MSRV` for schemars, so this is not a change.

**Comment by Kixunil** [comment]
> This library should always compile with any combination of features on **Rust 1.41.1**.

`schemars` is a feature and it being enabled is one of the possible combinations of features.

**Comment by apoelstra** [comment]
:( ok I'll update the text. I don't know how that happened, schemars has repeatedly broken MSRV

**Comment by tcharding** [comment]
I'd hazard a guess that I probably got trigger happy and put it in the CI script when I noticed it wasn't in `FEATURES` - just a guess though :)

**Comment by apoelstra** [comment]
I think probably when we moved the MSRV to 1.41 we noticed that schemars "worked" and didn't think about it.

**Review by Kixunil — APPROVED** [review]
ACK 05f543c94e6c06f07560c35fbf0f404a21fdc000

**Comment by apoelstra** [comment]
lol who actually has authority to ACK PRs in this crate?

I wouldn't mind adding @Kixunil or @tcharding if they want.

**Comment by apoelstra** [comment]
Added both of you with "Write" permissions.

**Pull request merged**
