### PR TITLE
Allow initializing a SHA256 engine with a state

### LINKED ISSUE #34: Allow initializing engine with midstate
Right now it seems like callers can not set the state of hash engines, f.e. SHA256. Sometimes it's useful to initialize a hash engine "as if" you've already hashed some data. If you've obtained the midstate this can speed up hashing significantly in some cases.

### PR DESCRIPTION
**Pull request by jonasnick**
Fixes #34 (for SHA256)

### CODE REVIEW

**Comment by sgeisler** [comment]
utACK, but I kinda dislike that it's not part of the `Hash` or `HashEngine` trait. That makes the API less predictable: why does sha256 have this function but no other hash implementation? They are all able to extract the midstate.

**Comment by jonasnick** [comment]
> why does sha256 have this function but no other hash implementation?

The main application I'm interested in is taproot hashing which can use tagged hashing a la `H(H("taproot") || H("taproot") || rest)` and presumably uses SHA256. This PR can certainly be pushed back until there's concrete proposal with community support.

**Comment by sgeisler** [comment]
After experimenting with different generalizations a bit I came to the conclusion that we can't make `from_midstate` part of the `HashEngine` trait without some refactorings/conceptual changes. 

The main problem is that I can't find a good way to implement `from_midstate`for HMAC since it would need a key to initialize the outer engine. Maybe the midstate of the HMAC engine should be 
```rust
(<<T as Hash>::Engine as HashEngine>::MidState, <<T as Hash>::Engine as HashEngine>::MidState)
```
so it could be actually used to reconstruct the hash engine?

**Comment by apoelstra** [comment]
@sgeisler +1 to that

**Comment by stevenroose** [comment]
I agree that `HashEngine::from_midstate` would be more intuitive for this than a method on `Hash`. It also helps hiding the method from the average user, fwiw. Also using `HashEngine::Midstate` as input instead of `[u32; 8]` would be preferred, even though that probably makes it less efficient to create engines with it.

**Comment by stevenroose** [comment]
For now I have this PR cherry-picked in https://github.com/rust-bitcoin/bitcoin_hashes/pull/39.

If we come up with a way to include `from_midstate` in the trait, that'd be great. But for now I can test the taproot hashes and midstate usage for elements using #39.

**Comment by apoelstra** [comment]
Merged as part of #39

**Pull request closed without merging**
