### PR TITLE
bump version to 0.9.1

### PR DESCRIPTION
**Pull request by apoelstra**

### CODE REVIEW

**Review by dr-orlovsky — APPROVED** [review]

**Comment by dr-orlovsky** [comment]
I think we also need to update MSRV in the README

**Comment by stevenroose** [comment]
Yeah I'd also prefer to have the MSRV edited in the readme before doing this release.

**Comment by stevenroose** [comment]
Maybe also quickly address https://github.com/rust-bitcoin/bitcoin_hashes/issues/98.

**Comment by apoelstra** [comment]
rebased, addressed #98, updated README

**Review by dr-orlovsky — APPROVED** [review]

**Review by stevenroose — APPROVED** [review]

**Pull request merged**
