### PR TITLE
Implement std::ops::Deref<Target=Inner> for Hash impls

### PR DESCRIPTION
**Pull request by stevenroose**
Relevant for #45.

### CODE REVIEW

**Comment by apoelstra** [comment]
Can you add a unit test that confirms that this gives us `to_vec`? Are there other things, e.g. the indexing traits, that we can now drop?

**Comment by dpc** [comment]
As per https://doc.rust-lang.org/std/ops/trait.Deref.html

"Implementing Deref for smart pointers makes accessing the data behind them convenient, which is why they implement Deref. On the other hand, the rules regarding Deref and DerefMut were designed specifically to accommodate smart pointers. **Because of this, Deref should only be implemented for smart pointers to avoid confusion.**"

I'm not saying that I agree/disagree, but just want to make sure you're aware of the official party line.

**Comment by apoelstra** [comment]
Oh, yeah, I think when I approved this I had it in my head that we were implementing `Deref<[u8]>` (i.e. "hashes are kind of like a slice"), which I think is consistent with the party line. For example `Vec<T>` implements `Deref<[T]>`. Implementing `Deref<[u8]>` should get us all the functionality requested in #45.

Agreed that `Deref<[u8; N]>` is not want we want.

**Comment by apoelstra** [comment]
I'm going to release a new major version of this lib today/next week to get `no_std` support. We can change the `Deref` impl then.

**Pull request merged**
