### PR TITLE
Revert "don't export core"

### PR DESCRIPTION
**Pull request by TheBlueMatt**
This reverts commit 1b36c27a51e14cb97e592c533045d81e5f257b71.

This broke build of rust-bitcoin. I'm gonna play with it to see if I can get CI to pass without this commit.

### CODE REVIEW

**Review by dr-orlovsky — APPROVED** [review]
utACK

**Review by apoelstra — APPROVED** [review]
ack e2575927fa671f2e24f1ad6c11cb2c96ee8b074c

**Comment by RCasatta** [comment]
https://github.com/rust-bitcoin/bitcoin_hashes/pull/122#issuecomment-831698713

Why all this rush?

**Comment by dr-orlovsky** [comment]
@RCasatta not just in bitcoin core, but in each crate using `bitcoin_hashes`, otherwise macro would not work. This is bad from macro hygiene point of view and I think @TheBlueMatt solution is supreme, since it has no such requirement.

The rush was caused by broken builds of rust-bitcoin right after `bitcoin_hashes` release, and since there was no PR opened there in parallel with this one, your comment was probably missed.

**Comment by RCasatta** [comment]
I didn't say this is worse, I just feel bad I put a clear "this is breaking" comment in five lines PR description that was missed and I haven't had time to comment the revert before the merge. I should have commented also the bump version PR...

btw the macro is not hygienic anyway since it requires Hash trait in scope

**Comment by TheBlueMatt** [comment]
Certainly not your fault the rest of us missed it.

As for hygiene, we should fix that, but at least it’s no worse than it was.

**Comment by sgeisler** [comment]
> also, this wasn't the only option to fix downstream build, wouldn't yanking 0.9.5 would have been sufficient as a first step?

I have to agree with this very much. Breaking downstream sucks, but the current situation is not much better tbh, there is still a broken version out there and there is rust-bitcoin/rust-bitcoin#602 because of that apparently. Yanking would have been much easier.

**Comment by apoelstra** [comment]
@RCasatta the break was not that anybody downstream was actually using the exported `core`. That is the breakage that you warned about and we explicitly decided to live with it.

The break was that we were exporting the new `core` in our macros, which is part of the general "rust macros cause downstream breakage that unit tests and compile-tests cannot fix" problem. This was not mentioned anywhere in the original PR, by anybody, and that is what we are fixing now.

**Comment by apoelstra** [comment]
@sgeisler the fuzztest is not downstream breakage. Anything downstream that depends on the fuzztest feature is dangerously and security-compromisingly broken. Yes, we have to update the rust-bitcoin fuzztests because of this. This was expected and uninteresting.

The hygeine issue is part of the general "rust macros cause downstream breakage that unit tests and compile-tests cannot fix" problem.

**Comment by RCasatta** [comment]
> @RCasatta the break was not that anybody downstream was actually using the exported core. That is the breakage that you warned about and we explicitly decided to live with it.

No, I wrote rust-bitcoin would need `extern crate core` not that someone is using the core re-exported.

**Pull request merged**
