### PR TITLE
Repository cleanup w/ help from Clippy

### PR DESCRIPTION
**Pull request by dongcarl**
Various cleanups inspired by clippy output. Added sane clippy allows in the last commit. `cargo clippy` should have empty output after this is merged.

### CODE REVIEW

**Comment by stevenroose** [comment]
Hmm, your clippy annotations broke the 1.22 build. Perhaps for now we better just drop them? Or comment them or something for reference.

Otherwise ACK fee48f0b46958f257df2963ee51a4341254b397b

**Comment by apoelstra** [comment]
Are we supposed to "not take references if it's small enough to pass by value" or "use `iter` rather than `into_iter` to avoid moving a 2-word value"? :)

**Comment by apoelstra** [comment]
Less joking aside, I think

* We should drop the `into_iter` commit because to the extent it has any effect at all, it's just introducing an unnecessary indirection. If Clippy recommends this it's a bug in clippy.
* We should drop the "take `siphash` by value" commit because it's a minor thing and the only breaking change in this PR. (Though I suppose making `engine` a trait method of `Hash` is technically a breaking change as well, if somebody had implemented `Hash` on their own type and implemented an `engine` method on that which will now conflict.)
* We should drop the clippy-lint commit because it breaks compilation. Though I'm glad to learn that in recent versions of rustc these are no longer compile errors; that prevented me using Clippy for a long time.

**Comment by dongcarl** [comment]
@apoelstra

> We should drop the `into_iter` commit because to the extent it has any effect at all, it's just introducing an unnecessary indirection. If Clippy recommends this it's a bug in clippy.

I believe this lint is for readability, as we expect `into_` methods to move, but it clearly doesn't in this case. But happy to drop if you still think it should be dropped. Source: https://rust-lang.github.io/rust-clippy/master/index.html#into_iter_on_ref

> We should drop the "take `siphash` by value" commit because it's a minor thing and the only breaking change in this PR.

Sure, let's do that.

> We should drop the clippy-lint commit because it breaks compilation. Though I'm glad to learn that in recent versions of rustc these are no longer compile errors; that prevented me using Clippy for a long time.

Done.

> We may need to drop `derive(Clone)` on sha512 because in the distant past (not sure about 1.22) `Clone` was not implemented for `[u8; 128]`.

It is implemented for `1.22.0`, I don't think we need to drop this.

**Comment by apoelstra** [comment]
Ok, "for readability" makes sense. All looks good to me then.

**Pull request merged**
